version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - /TODO:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: nm
            MYSQL_USER: maxtrussell
            MYSQL_PASSWORD: 

    nutrition-mate:
        depends_on:
            - db
        image: nutrition-mate:latest
        ports:
            - "5000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: nm
            WORDPRESS_DB_PASSWORD: super_secure_password
            WORDPRESS_DB_NAME: nm
